#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored
from colorama import init
from nltk.tokenize import TweetTokenizer

def main():

    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    analyzer = Analyzer(positives, negatives)
    
    screen_name = sys.argv[1]
    
    tw_count = 50                                               # number of tweets to get from timeline
    
    tweets = helpers.get_user_timeline(screen_name, tw_count)
    if not tweets:                                              # if no tweets were returned
        exit_m = "No tweets for @{}".format(screen_name)
        sys.exit(exit_m)
    for tweet in tweets:                                        # for every tweet
        score = analyzer.analyze(tweet.lower())
        if score > 0.0:
            print(colored(score, "green"), end = " ")
            print(colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "red"), end = " ")
            print(colored(tweet, "red"))
        else:
            print(colored(score, "yellow"), end = " ")
            print(colored(tweet, "yellow"))
        
if __name__ == "__main__":
    main()
